### ISSUE TITLE
4:3 Cropped Request. Looks much better than just 4:3!

### ISSUE THREAD

**Issue by Nashismo** [bubble2k16/snes9x_3ds#1]
Hi mate and thanks for this wonderfull project.

In summary, I was playing a few Blarg (another snes emu) Snes injections on my New 3DS and I saw an option to choose 4:3 Cropped. And to my surprise, it zooms in, takes away the horrible black bars (and just  bit of the screen palette).

Thing is, this resolution (so to speak) looks MUCH better and less muddy than your 4:3 or fullscreen options in Snes9x (that was actually my surprise). You can even see some scanlines and the texts look much cleaner.

Is no 1:1 quality but it definetely looks much better than the options currently available for making the screen bigger.

My deep thanks, and I hope you consider this request!
Cheers!

Ignacio.

**Comment by bubble2k16** [comment]
Hi Nashismo, thanks for the feedback. Well, I'll have a look at it when my hands are free. Too busy with work now with anything related to this port. It doesn't seem to difficult to implement. :)

**Comment by Nashismo** [comment]
That would be so amazing! Even in games like Street Fighter for example and many other you actually don't even lose game screen because they natively have the black horizontal bars! So this honestly would be really a nice addition.

You would actually be beating the original Nintendo Snes emu with this :) 

All in all, thanks for your time and take care always of your health, a good advice for health from my grandfather: Good food and nutrition is the best healer! Or to stay healthy of course! So don't forget to eat!

Cheers.

**Comment by bubble2k16** [comment]
Yes, the latest v1.00 has cropped 4:3, cropped fullscreen and number of other screen stretching options. :)
