### ISSUE TITLE
Possible to increase fast-foward speed?

### ISSUE THREAD

**Issue by starmandeluxe** [bubble2k16/snes9x_3ds#104]
Fast-forward is a welcome feature but it seems to be unconfigurable and is at a hardcoded set speed, which isn't very fast at all (maybe maximum 2x?). Is it possible to change this to make it faster?

**Comment by AdmiralCurtiss** [comment]
From what I remember, the fast-forward just simply disables the framelimiter, so your 3DS is running the emulation as fast as it can. You could make it slower (eg. limit to maximum of 1.5x or whatever), but not faster without optimizing the emulation itself.

**Comment by starmandeluxe** [comment]
That makes sense. Thanks for the explanation!
