### ISSUE TITLE
Support for Super Metroid / A Link to the Past crossover (again)

### ISSUE THREAD

**Issue by KasaiKemono** [bubble2k16/snes9x_3ds#118]
I saw this issue already outlined in #94 , and the fix in #103 
For some reason though, I keep getting the same behaviour on Snes9x 1.30, is there any chance to fix this?

**Comment by FateForWindows** [comment]
The fix was merged after 1.30's release, so it wasn't present in that build. I'll be updating this soon (in Bubble's absense), but in the meantime I'd recommend using this build for now.

[snes9x_3ds_3192021.zip](https://github.com/bubble2k16/snes9x_3ds/files/6174658/snes9x_3ds_3192021.zip)
