### ISSUE TITLE
Bs Zelda isnt support

### ISSUE THREAD

**Issue by RetroMarioBros** [bubble2k16/snes9x_3ds#12]
I get black screen in this games 
other games of satellaview run perfectly

**Comment by bubble2k16** [comment]
Yup it's a known issue. Not sure how to make this work for now, as I am not familiar with Satellaview. :)

**Comment by RetroMarioBros** [comment]
This game is compatible with Pocketsnes core (Retroarch) ( I think that is based in snes9x 1.43)

**Comment by bubble2k16** [comment]
Not sure about Pocketsnes Retroarch core, but the original Snes9x 1.43 on Windows doesn't run BS Zelda either.

**Comment by RetroMarioBros** [comment]
In Snes9x 1.52.4 run too 
Zelda (BS map 1 and BS map2)
i test in retroarch snes9x 2010 1.52.4

**Comment by bubble2k16** [comment]
It probably does. But Snes9x v1.52 onwards, the codes have changed to favor accuracy (less speed) over better performance. It won't be possible to port this without a performance hit.

Does BlargSNES run BS Zelda map 1 & 2?

**Comment by RetroMarioBros** [comment]
No , black screen
 on BlargSNES
also!!

**Comment by bubble2k16** [comment]
Any ideas if there are any BS games that work in BlargSNES but not in Snes9x for 3DS? Someone on GBAtemp mentioned something like that... was it you? ;)

**Comment by RetroMarioBros** [comment]
No , sorry
I use snes9x for satellaview games. 
I think than snes9x run better than BlargSNES

**Comment by ShadowOne333** [comment]
Sadly, neither blargSNES is compatible with any of the BS Zeldas afaik.
The only thing that I could find which could be of help for the project (and to hopefully make BS Zelda compatible) is the following files:

https://github.com/LuigiBlood/snes9x/blob/master/bsx.cpp
https://github.com/LuigiBlood/snes9x/blob/master/bsx.h

Ancient Stones Tablets is compatible with Snes9x for O3DS. It does boot, so it seems only BS Zelda is the one not working.

**Comment by FateForWindows** [comment]
BS Zelda (not Ancient Stone Tablets) works in the SNES9X 2002 and 2010 libretro cores, but not 2005 or 2005+. This must have been a change done in between releases that broke BS Zelda.

SNES9X runs only a tiny bit better than blargSNES, the main noticable thing is saving, with the option to disable sram auto saving and just generally faster saving. The libretro cores are unbearable on the O3DS but are a bit better on the N3DS accuracy-wise.

**Comment by FateForWindows** [comment]
It's taken a bit too long for me to finally say this, but the fixes are ready. I'll push them as soon as testing is complete.

**Comment by bubble2k16** [comment]
Do try out v1.20 and report to see if there's issue. So far, BS Zelda (1-4), Map 2 (1-4), and Ancient Stone Tables (1-4) all work.

The only one that boots to black screen is BS Zelda Remix.

**Comment by Ryuzaki-MrL** [comment]
Can confirm BS Zelda Map 1 patched rom from bszelda site is working fine on old 3ds 11.5 with snes9x v1.20.
Timer, spells, events, etc. all working correctly.

**Comment by bubble2k16** [comment]
I'll close this issue now. :)
