### ISSUE TITLE
Support for stereoscopic 3D in Jim Power: The Lost Dimension in 3-D.

### ISSUE THREAD

**Issue by vaguerant** [bubble2k16/snes9x_3ds#14]
All right, from the outset, I want to acknowledge that this is pushing it. It involves implementing a moderately complicated feature just to support one game which isn't very fun to play at all. I fully understand if this seems like a stupid waste of time, I'm really only suggesting it for the novelty factor. It's a 3D game, on a system not known for them, which we can now play back on a 3D display.

Jim Power: The Lost Dimension in 3-D is a SNES game which came with a pair of 3D glasses. Rather than the anaglyph (e.g. red/green) glasses everybody remembers from the '90s and earlier, the glasses included with Jim Power employed the [Pulfrich effect](https://en.wikipedia.org/wiki/Pulfrich_effect).

<img src="https://i.imgur.com/gG2zjei.jpg" width="400px">

As you can see here, this means one dimmed lens (like a pair of sunglasses) and one clear lens. The lenses are **not colored at all**. To summarize the way the Pulfrich effect works, which sounds like lies and nonsense until you try it for yourself:
* the effect is only active when the image is in motion
* the human eye actually takes longer to process the dimmed image
* Jim Power uses a parallax layer which moves faster than the foreground
* when the brain composites the two images through Pulfrich glasses, one image (the right, "immediate" eye here) looks as if it was taken from a slightly different angle as the other (the left, "delayed" eye)
* the result is a (temporary) 3D effect, visual whenever the backdrop is in motion

As you might be able to guess, it's kind of a dumb way to do 3D, but it does work.

Apologies for the long intro.

To achieve the same effect on the 3DS, my supposition is that a delayed image could be kept behind for the left eye's framebuffer and displayed simultaneously with the current image (for the right eye), resulting in a sort of "glasses-free Pulfrich effect". It would work exactly the same as it does with the glasses, i.e. only when there is movement to support it. The effect would disappear if the player stood still.

The part of this I don't know at all is how long a delay would be "correct" to match the correct "3D depth" created by the Pulfrich glasses that come with the game. The way the Pulfrich effect works, the darker the dimmed image, the longer it takes to be processed, and the more pronounced the illusion of 3D stereoscopy becomes. I have no idea how much VRAM you have available to keep storing frames for the left eye, but perhaps a single frame would be plenty to cause the Pulfrich effect. Of course, on 3DS, the delay equates to the dimness of the image, so the longer the delay, the more pronounced the effect.

But anyway, all of this assumes you'd be interested in implementing a stupid feature for a stupid game nobody wants to play. 😄

If you'd like to try the Pulfrich effect for yourself, you can find any standard pair of sunglasses, and hold them so that your **left** eye is being dimmed by them, while the right is not. Any [video of Jim Power](https://www.youtube.com/watch?v=8tN_TPTIrYs) should be able to show you the effect. Do remember that the effect only appears when in motion, so this gameplay video shows it frequently appearing and disappearing. The effect is perhaps at its most stable beginning at 17:40, a level where movement is constant rather than dictated by the player, such that it's not appearing and disappearing throughout.

**Comment by bubble2k16** [comment]
As I did for the other issue, I'll close this too. :)
