### ISSUE TITLE
Support for stereoscopic 3D in HyperZone.

### ISSUE THREAD

**Issue by vaguerant** [bubble2k16/snes9x_3ds#15]
This one actually might be a bit more plausible than Jim Power: HyperZone is a SNES mode-7 flight game by HAL Laboratory which includes actually includes a secret 3D mode—with proper, interleaved left/right frames. However, no way to actually view the 3D was ever provided by Nintendo. Interleaved 3D of this kind was usually viewed with shutter glasses (glasses that literally open and close each lens constantly, in sync with the television, so that each eye only sees its intended image).

Modern systems still use interleaving for 3D; e.g. Moflex FMV footage on 3DS is all left/right interleaved.

As you can see [here](https://tcrf.net/HyperZone#3D_Effect) (full disclosure: I'm an administrator at the linked wiki; if you feel this is a conflict of interest, feel free to edit the issue to remove the link), a button code entered on the title screen enables the 3D display.

From this point on, gameplay is in interleaved 3D (left frame/right frame/left frame/right frame). Hopefully, if you're interested, it should be possible for you to split odd/even frames into separate framebuffers in Snes9x 3DS. Sorry, I'm not sure which frames are meant for which eye. Also, any frameskipping would send the effect straight to hell, so it might be best to either: disable frameskip entirely, or only skip **even numbers** of frames in order to keep from losing the effect.

For the hell of it, here's two frames that I've converted to an MPO, you should be able to view it in 3D by opening this issue in the 3DS browser.
![Hyperzone in 3D](https://cloud.githubusercontent.com/assets/5259025/22510478/33038f78-e8e6-11e6-9907-fad878e1d0c5.jpg)

**Comment by bubble2k16** [comment]
Hi vaguerant, I doubt I will add support for 3D rendering on the 3DS, whether by using red/blue anaglyphs techniques, or using the native 3DS's 3D functions. If there are any other devs interested they can try. :)

**Comment by vaguerant** [comment]
That's too bad, @bubble2k16, but thanks for the quick response. I'll keep my fingers crossed for somebody to take this up. The 3DS could have been the perfect opportunity to revisit the history of stereoscopy in video games, but I guess Nintendo didn't want to remind anybody about the Virtual Boy. 😉

**Comment by bubble2k16** [comment]
No problem. In the meantime, I'll just close this. :)
