### ISSUE TITLE
Weird Layers

### ISSUE THREAD

**Issue by junioresp** [bubble2k16/snes9x_3ds#2]
First i wanna thank you guys for your wonderful work, almost all games i've been playing are working flawlessly, all the donkey kong series are working perfect! and the sound are almost perfect as well.
But, recently i have notice some issues with some games, the layers aren't correct, i notice that with Chrono Trigger and Super Mario Bros 3 (All-Stars), here some pics

Crono depressed on his bed
http://i.imgur.com/93Qf7c8.jpg

Mario breaking the laws of physics
http://i.imgur.com/9zuNpcM.jpg

edit: just notice that with DKC3 also

**Comment by bubble2k16** [comment]
Hi Junioresp, yes the layering of sprites is a known issue. :) But I am currently so busy with work that I have little time to fix this. But I've noted that and once I find time to get back to this, this layering issue will be the number 1 thing to fix. :) In the meantime, I'll be keeping this issue open.

**Comment by Nashismo** [comment]
I just came (from my other request) to say we greatly appreciate your work! I am from south america but (even though I am bit low on income) it would be nice if you could receive some form of aid, maybe through Paypal or something so everyone willing can support your work.

Cheers and let's only hope you can get some free time and rest, then remember to eat hehehe, and THEN :) you continue with this wonderful emu.

**Comment by bubble2k16** [comment]
Fixed in v0.70. Most of the games with priority issues (Shadowrun, Chrono Trigger, Super Mario All Stars, and possibly others) are resolved.
