### ISSUE TITLE
[Suggestion] Add mozaic effect transitions

### ISSUE THREAD

**Issue by madkoding** [bubble2k16/snes9x_3ds#22]
Its seems Super Mario World missed this feature, meaby removed to optimize speed?

![tumblr_n2utp9moqt1rrftcdo1_500](https://cloud.githubusercontent.com/assets/333442/23705177/4f4b2292-03e7-11e7-86cf-7f8d443a0453.gif)

**Comment by FateForWindows** [comment]
It's listed in the list of missing features that will probably be added. It also happens in Super Metroid's menus and it's very annoying.

**Comment by bubble2k16** [comment]
It's missing because it uses the GPU for rendering, which doesn't natively support mosaics.  Won't be added. :)

**Comment by FateForWindows** [comment]
rip

**Comment by Klauserus** [comment]
Oh sad.I have a technic question about that.The vc version of smw can show this effect.Whats the different between the emulator from big n and yours? Using gpu? 

Ps: thank you for this nice software

**Comment by bubble2k16** [comment]
This emulator was meant for the old 3DS, and that meant we had to trade off a number of things to achieve the speed. And this mosaic effect was one of it. :)
