### ISSUE TITLE
Could we get the ability to set a default ROM directory?

### ISSUE THREAD

**Issue by Rust-and-Sunset** [bubble2k16/snes9x_3ds#3]
I assume I'm not alone in not keeping ROMs in the SD card's root directory- could we get the option of defining a default directory for the file browser to open at automatically? It'd make navigating to games a bit less frustrating- particularly for people that have them nested several directories deep.

**Comment by bubble2k16** [comment]
Fixed in v0.70. The emulator saves the last loaded ROM's directory, and navigates straight to it when it starts up.
