### ISSUE TITLE
When I lauch Snesx9 it loads but then crashes

### ISSUE THREAD

**Issue by SomeRandomSkull** [bubble2k16/snes9x_3ds#32]
Every time i try to load Snesx9 it loads then it crashed with the top screen being a glitched out ,and the bottom just red.
this started after i updated my N3DS to 11.4.0-37U. I've tried different versions but nothing works and ideas?

**Comment by FateForWindows** [comment]
*snes9x, not snesx9

I do not have a solution but if you made a NAND backup before the upgrade, restore it.

**Comment by SomeRandomSkull** [comment]
@FateForWindows Have no backup and even backups that i had before still don't work. backups that i had before meant going back to that backup.)  also this began when i updated my N3DS like i said.

**Comment by bubble2k16** [comment]
Is your 3DS running a custom firmware like Luma? If so, try to use FBI to download Snes9x for 3DS from TitleDB to see if it works.

Many home-brew launcher apps don't work on 11.4.

**Comment by SomeRandomSkull** [comment]
@bubble2k16 No custom firmware and i figured out that Snes9x doesn't work on 11.4 so for now gonna use Snes9x EX+ until and update for 11.4 comes out

**Comment by FateForWindows** [comment]
Strange, works perfectly for me on both O+N3DS 11.4. Must not be compatible with 11.4 *hax payloads. That's most likely the issue since they break a lot of apps.

**Comment by bubble2k16** [comment]
@FateForWindows you are using Admiral Curtiss' fork, and that works under HBL? Does the original version 1.11 work for you?

**Comment by FateForWindows** [comment]
AdmiralCurtis doesn't have all his commits in a single fork, and I haven't tried, but yeah, for yours using 11.2 payloads on 11.4 Luma works but 11.4 payloads on 11.4 doesn't work. I'm only using the .cia of 2 fixes he made but haven't copied the 3dsx over

**Comment by bubble2k16** [comment]
smea updated payloads for 11.4. @SomeRandomSkull you might want to see if it helps you?

**Comment by SomeRandomSkull** [comment]
@bubble2k16 works now
