### ISSUE TITLE
[Sugestion] Disable the 3d slider to avoid frame drops

### ISSUE THREAD

**Issue by MightyPrinny** [bubble2k16/snes9x_3ds#33]
The emulator usually drop frames on the o3ds, it looks like frameskip but i have frameskip disabled and i think it is because of the 3d slider, i know this because since libretro implemented it on retroarch the same thing started to happen.

A posible solution would be to add the feature as an option or maybe release two builds in every release, one with the feature and another without it.

**Comment by FateForWindows** [comment]
I will try to add this as an option but I cannot reproduce your issues.

**Comment by saphtea** [comment]
I don't notice a frame drop because of this, but sometimes the emulator will bug out with my 3D slider up and display a part of the game on one eye and not the other. It may be best to disable 3D slider just to avoid this issue!

**Comment by d3xMachina** [comment]
I have a n3ds and when I set the 3D slider to min, it displays only for my left eye but I have no problem when I set it off or up. However it looks sharper if I set it higher than the min which is nice. I didn't test enough to see if there is an impact on the frame rate though.
