### ISSUE TITLE
Trying to add cloud saving

### ISSUE THREAD

**Issue by Joeaculberson** [bubble2k16/snes9x_3ds#41]
I've been attempting to add cloud save functionality to the libctru-1.0.0 build of the emu, but it's proving quite difficult with the limited documentation/examples online. I see there's some examples of sockets and httpc for libctru-1.3.0 (https://github.com/devkitPro/3ds-examples/tree/master/network), though it's not building when I upgrade. Has any effort been put into upgrading and/or adding cloud save functionality?

So far debugging has been a pain because network capabilities are not present on the citra emulator, so each build must be tested on the device for every change made. That and even with VS2017, the intellisense just isn't all that great for detecting if my syntax is correct with these different libraries.

My idea was to have it automatically sync up to dropbox/googledrive/etc if a user has entered their credentials in a config doc. Either that or just a selection in the menu where they can manually sync if that is less intensive on the emu. This would be great so players could seamlessly switch from 3ds to any device (assuming the other device also had cloud saving -- was mainly looking at snes9x on wii and Wiiu since the save files are the same). Let me know if you have any thought or ideas that could help me along in this effort. Thanks!

**Comment by bubble2k16** [comment]
This has been asked before, but I don't think I would like to embark on networking stuff. :) You could try and maybe take a look at those home-brew with networking capabilities like FBI, freeShop, etc.
