### ISSUE TITLE
[Suggestion] Button config, similar to VirtuaNes.

### ISSUE THREAD

**Issue by Trinsid** [bubble2k16/snes9x_3ds#42]
It'd be nice to have button configuration options, _especially_ when playing Mega Man X. My hand keeps cramping because I'm used to using X for jumping, not B!

**Comment by AdmiralCurtiss** [comment]
While I agree, I'm pretty sure Mega Man X has built-in button remapping functionality.

**Comment by AdmiralCurtiss** [comment]
Implemented.
