### ISSUE TITLE
Binaries in repository?

### ISSUE THREAD

**Issue by AdmiralCurtiss** [bubble2k16/snes9x_3ds#46]
Is there a particular reason we have the compiled binaries in the repository? It's generally discouraged to do that in git, since git is bad at tracking binary changes and it noticeably bloats the repository filesize, and on Github we have a nice Releases tab where we can just upload the binaries for specific revisions instead.

Would anyone mind if we removed them from git and moved to putting them in the Releases tab instead?

**Comment by FateForWindows** [comment]
There hasn't been a full release. Those are meant to be the latest beta versions. Overall, though, I honestly think we should move them.

**Comment by AdmiralCurtiss** [comment]
#50 got merged so I'll consider this complete.
