### ISSUE TITLE
Odd sound lag issue upon wakeup from sleep mode.

### ISSUE THREAD

**Issue by Joelgp83** [bubble2k16/snes9x_3ds#5]
Hi, I'm running into a weird lag / de-sync condition in regards to sound.  To replicate:

1. Launch Snes9x from homebrew launcher
2. Load a ROM (I used both Lufia 2 and Super Mario World as test cases).
3. Get in game, play for a minute (or more if you distracted) then, without pausing the emulator, close the system to activate sleep mode.
4.  Let it sleep for a minute, then open the system to wake it up.

The sound should now be de synced, with obvious lag between events and their associated sounds.  Touching the bottom screen to open the emulator menu and then returning to the game appears to fix the issue, but to me it still seems like there's a bug in how the emulator's sound buffer isn't properly recovering from sleep mode.

All in all, love the emulator though, and I appreciate the work done so far, so keep up the good work! :)

**Comment by bubble2k16** [comment]
I have no idea how to fix this yet. The best you can do is to tap on the bottom screen after waking up. It should help to resync the sound again.
