### ISSUE TITLE
Any chance I can get the .elf included in builds?

### ISSUE THREAD

**Issue by senseijimjom** [bubble2k16/snes9x_3ds#52]
Really enjoy the .elf, as it makes great ease for forwarding. Any chance I can get the latest builds with the .elf? Thank you so very much!

**Comment by Shroomalistic** [comment]
i second that!  I have no clue how to compile it myself

**Comment by senseijimjom** [comment]
I've compiled, but I'm not sure how to ignore the .gitignore. Just need that delicious .elf! :D

**Comment by AdmiralCurtiss** [comment]
If you already have the elf you're done, aren't you?

I have nothing against putting the elf in the releases, but I am against checking it into the repository. See #46.

**Comment by senseijimjom** [comment]
I don't have the latest. Can you hook me up @AdmiralCurtiss? Then I can leave all you fine people alone :)

**Comment by AdmiralCurtiss** [comment]
The latest what, elf? Clone/download a copy of the repository, download and install the newest devkitPro, remove the `-DLIBCTRU_1_0_0` from the `CFLAGS` in the `Makefile`, then just run `make` in the same folder as the `Makefile`. That should be it, and that way you can repeat that for every new change you want a compiled version of.

**Comment by senseijimjom** [comment]
Got it working, thank you for that!

**Comment by Shroomalistic** [comment]
c:\snes9x>make
shaderfast.v.pica shaderfast.g.pica
shaderfast2.v.pica shaderfast2.g.pica
shaderfastm7.v.pica shaderfastm7.g.pica
shaderslow.v.pica
shaderslow2.v.pica
shaderslow3.v.pica
shaderslowm7.v.pica
3dsmain.cpp
arm-none-eabi-g++ -MMD -MP -MF /c/snes9x/build/3dsmain.d  -c /c/snes9x/source/3dsmain.cpp -o 3dsmain.o
c:/snes9x/source/3dsmain.cpp:11:10: fatal error: 3ds.h: No such file or directory
 #include <3ds.h>
          ^~~~~~~
compilation terminated.
make[1]: *** [3dsmain.o] Error 1
make: *** [build] Error 2

c:\snes9x>make
3dsmain.cpp
arm-none-eabi-g++ -MMD -MP -MF /c/snes9x/build/3dsmain.d  -c /c/snes9x/source/3dsmain.cpp -o 3dsmain.o
c:/snes9x/source/3dsmain.cpp:11:10: fatal error: 3ds.h: No such file or directory
 #include <3ds.h>
          ^~~~~~~
compilation terminated.
make[1]: *** [3dsmain.o] Error 1
make: *** [build] Error 2
 this is what I get when I try to compile everytime

**Comment by FateForWindows** [comment]
Does the directory have spaces?

**Comment by Shroomalistic** [comment]
What do ya mean by spaces?  The name of the directory?

**Comment by FateForWindows** [comment]
Actually, a better word would be path. Does the path to the source code have any spaces?
