### ISSUE TITLE
limit of list of roms

### ISSUE THREAD

**Issue by stelecroco** [bubble2k16/snes9x_3ds#6]
Hi, i'm running your application and i have an issue.

I unzip all the romset (SFC roms) in a folder to test it and the list stop at B (Batman Forever)
I can just list the first 1000 roms (around).

Keep up the good work. Thank you.

**Comment by bubble2k16** [comment]
Hi Steleroco, yes there's currently a limit of 1000 ROMs. The workaround for now is to place it into different folders. Scrolling 1000 ROMs on the keypad is a little difficult to use, no? ;)

**Comment by AdmiralCurtiss** [comment]
This should be fixed. I haven't personally tried a huge folder, but it should no longer have a limit.

**Comment by bubble2k16** [comment]
Do try this in v1.20

Edit: Just want to add that having such a huge list of ROMS will cause the emulator to slow down when it loads the full list of files.
