### ISSUE TITLE
Support for English version of Far East of Eden Zero

### ISSUE THREAD

**Issue by 13xforever** [bubble2k16/snes9x_3ds#65]
[Quoting](https://twitter.com/Doug_RPG/status/921574679755874304) one of the translation team members:

> The files I changed to add support for TMZ - English Translation. Just do a diff and update you Snes9x core

Said files are attached to this issue.

[CodeChangeTmz.zip](https://github.com/bubble2k16/snes9x_3ds/files/1404276/CodeChangeTmz.zip)

**Comment by bubble2k16** [comment]
The v1.20 should support this.

**Comment by 13xforever** [comment]
RTC is broken for the English patch. It initializes to 01-27-2056 12:24 PM instead of 11-12-2017 8:14 PM.
Original Japanese version works as expected (at least for the day/month/time part).

**Comment by 13xforever** [comment]
Actually, ignore this, I accidentally copied `.rtc` along with `.srm` from a PC version.
