### ISSUE TITLE
3DS crashes on last commit

### ISSUE THREAD

**Issue by asdolo** [bubble2k16/snes9x_3ds#67]
Pretty much the title. In a fresh install when I open the emulator and press "A" or any D-Pad button, the 3DS crashes.

I'm not even able to navigate through my SD to select a ROM.
The list of roms is just "/". If I press "A" to select the "/" folder, then it crashes.
If I press the D-Pad to go to another tab, it crashes too.

I'm on a n3DS, running Luma v8.1.1.

**Comment by AdmiralCurtiss** [comment]
Try uncommenting the `#define RELEASE` in 3dssnes9x.h; if that's not it then I cannot reproduce your problem when compiling with libctru 1.3.0.

**Comment by asdolo** [comment]
Hmm, I'm compiling with libctru 1.0, I'll try that!
