### ISSUE TITLE
ZL and ZR not working

### ISSUE THREAD

**Issue by KevinBlue18** [bubble2k16/snes9x_3ds#71]
ZL and ZR not registering when assigned.

**Comment by ThunderDragonRandy** [comment]
From what I read in other posts, the CIA version of the emulator doesn't register the ZL or ZR button. The ZL and ZR should work on the Homebrew Launcher version but I haven't tested the Homebrew Launcher version.

**Comment by rrooij** [comment]
I'm running the latest version of Luma and the latest official CIA release of snes9x_3ds. ZL and ZR works fine when mapping to something. I would suggest closing this issue since it works fine now.
