### ISSUE TITLE
Request: crop border pixels option

### ISSUE THREAD

**Issue by EoinODoodles** [bubble2k16/snes9x_3ds#8]
Would it be okay to add an option that allows you to crop away a row/number of rows of pixels from the top/bottom/left/right edge of the frame? There're often distracting visual oddities at the border of the picture in SNES games which were probably hidden on old CRT screens, and it'd be nice to be able to choose to render them as black pixels instead.

Thanks so much for creating this emulator by the way, I'm so delighted to be able to play SNES games on my old-3DS. :D

**Comment by bubble2k16** [comment]
The latest version v1.00 has additional stretching options, including cropped 4:3 and cropped full screen, and a few others. :)

**Comment by EoinODoodles** [comment]
Awesome, thank you so much!
