### ISSUE TITLE
3ds snes change icon

### ISSUE THREAD

**Issue by kimnue** [bubble2k16/snes9x_3ds#87]
hi.  
   i have install snes on my old 3ds by using cia file. everything work great. but i want to change the icon to be final fantasy picture. so i create picture and rename it to snes9x_3ds_top.png 

but the icon picture still not change to final fantasy picture..

T T

**Comment by FateForWindows** [comment]
This explanation is overdue by over a year, but to explain why it wouldn't load, snes9x_3ds_top.png was formerly used for the picture that filled the top of the screen when no ROM is loaded. As of 1.2.0, it was integrated into the app's ROMFS, so as a result, it's no longer used. You can still replace it by compiling the app from the source code.
