### ISSUE TITLE
Weird bugs in a few Games

### ISSUE THREAD

**Issue by CaviarTheCatgirl** [bubble2k16/snes9x_3ds#98]
So, I noticed so far that some games have really weird bugs.
For example Donkey Kong Country doesnt allow me to collect Lives, or Yoshis Island doesnt count my Stars. Im using the latest version, 1.30, and PAL Roms for DKC and YI.

**Comment by FateForWindows** [comment]
> So, I noticed so far that some games have really weird bugs.
> For example Donkey Kong Country doesnt allow me to collect Lives, or Yoshis Island doesnt count my Stars. Im using the latest version, 1.30, and PAL Roms for DKC and YI.

Try using NTSC ROMs. PAL shouldn't make a difference, but both work fine on the latest version with NTSC ROMs. Plus at the default settings NTSC ROMs run at 60 FPS, which displays more smoothly on the 3DS's 60Hz display.

**Comment by CaviarTheCatgirl** [comment]
> > So, I noticed so far that some games have really weird bugs.
> > For example Donkey Kong Country doesnt allow me to collect Lives, or Yoshis Island doesnt count my Stars. Im using the latest version, 1.30, and PAL Roms for DKC and YI.
> 
> Try using NTSC ROMs. PAL shouldn't make a difference, but both work fine on the latest version with NTSC ROMs. Plus at the default settings NTSC ROMs run at 60 FPS, which displays more smoothly on the 3DS's 60Hz display.

Okay, I found the problem! Those bugs werent caused because of PAl, those "Bugs" were caused because of my Cheats. I didnt knew Cheats activated automatically ._.
Thanks either way
